FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY src/ ./src/
COPY sql/ ./sql/

CMD ["uv", "run", "python", "-m", "src.seed.main"]
